Document: paparazzi-stm32
Title: Debian paparazzi-stm32 Manual
Author: <insert document author here>
Abstract: This manual describes what paparazzi-stm32 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/paparazzi-stm32/paparazzi-stm32.sgml.gz

Format: postscript
Files: /usr/share/doc/paparazzi-stm32/paparazzi-stm32.ps.gz

Format: text
Files: /usr/share/doc/paparazzi-stm32/paparazzi-stm32.text.gz

Format: HTML
Index: /usr/share/doc/paparazzi-stm32/html/index.html
Files: /usr/share/doc/paparazzi-stm32/html/*.html
