#!/bin/sh
/opt/local/bin/gdk-pixbuf-query-loaders --update-cache
/opt/local/bin/update-mime-database -V /opt/local/share/mime
echo "/opt/local/lib/ocaml/site-lib/stublibs"  >> /opt/local/lib/ocaml/ld.conf
echo 'export PATH=/opt/local/bin:/opt/local/sbin:$PATH' >> ~/.bash_profile



