#!/bin/sh

# creating pkg files stops macports from being able to do any post activate work 
# so we have to do it here
/opt/paparazzi/bin/gdk-pixbuf-query-loaders --update-cache
/opt/paparazzi/bin/update-mime-database -V /opt/paparazzi/share/mime
echo "/opt/paparazzi/lib/ocaml/site-lib/stublibs"  >> /opt/paparazzi/lib/ocaml/ld.conf

# set a nice theme for gtk to use so users not scared of by the ugly default
/opt/paparazzi/bin/switch2 /opt/paparazzi/share/themes/ClearlooksClassic

# create or modify .bash_profile to include path to the paparazzi tools. We will be running as root so we need to change the ownership and permissions
echo 'export PATH=/opt/paparazzi/bin:/opt/paparazzi/sbin:$PATH' >> ~/.bash_profile
chmod 755 ~/.bash_profile
user="$(who am i)"
set -- $user
owner=$1
chown $owner: ~/.bash_profile 


# check to see if they have a clone of the source for paparazzi if not get them one
if [ ! -d ~/paparazzi ]; then
    # use the git we just installed with paparazzi just in case they haven't got Xcode yet
    /opt/paparazzi/bin/git clone git://github.com/paparazzi/paparazzi.git ~/paparazzi
    chown -R $owner: ~/paparazzi
fi







